# ========== Profile ========== #
# avatar
avatar: /avatar/img.jpg
# author name
author: 
# signature
signature: Don't repeat yourself.
# SNS
social:
  email: fuwanqun@qq.com
  github: //www.github.com/babycannotsay
  # wechat and qq should be a path of an qr-code image
  wechat: /avatar/wechatQR.png
  qq: 
  weibo: 
  zhihu: 
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  v2ex: 
  linkedin: 
  others: 
  rss: 
# friends
friends:
  # friendA: 
  # friendB: 
  # friendC:
about:
  enable: false
  image: '/intro/about-bg.jpg'

# ========== Site ========== #
# title of the site
SEO_title: OnePiece
# main title
main_title: OnePiece
# subtitle
subtitle: 我做不到的由你来，你做不到的由我来。
# site haeder image
site_header_image: '/intro/index.jpg'
# post haeder image
post_header_image: '/intro/post-bg.jpg'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 

# ========== Analytics ========== #
# Busuanzi pv analytics
busuanzi: true
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: 
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /assets/img.jpg
# truncate length (the default is 300. If it's set to 0, there will not be abstruct)
truncate_length: 
# enable toc
toc: true
